# Generated by Django 2.2.6 on 2019-10-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelloModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='HelloModel.Person'),
        ),
    ]
