# Generated by Django 2.2.6 on 2019-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloModel', '0002_auto_20191030_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=16)),
                ('c_eat', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=16)),
                ('d_legs', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
