# Generated by Django 2.2.6 on 2019-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
