# Generated by Django 2.2.6 on 2019-11-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20191104_0941'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table=' axf_foodtypes',
        ),
    ]
