# Generated by Django 2.2.6 on 2019-11-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20191104_0949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtypes',
        ),
    ]
