# Generated by Django 2.2.6 on 2019-10-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Three', '0007_auto_20191029_1059'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
            ],
        ),
    ]
